[package]
name = "anton-emily-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0", features = ["secrets","json"] }
rusqlite = "0.31.0"
serde = "1.0.200"
rand = "0.8.4"
sha2 = "0.10.8"
